version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  ignore:
  - dependency-name: ember-cli
    versions:
    - ">= 0"
  - dependency-name: "@orbit/utils"
    versions:
    - 0.17.0-beta.12
  - dependency-name: "@orbit/indexeddb"
    versions:
    - 0.17.0-beta.10
    - 0.17.0-beta.9
  - dependency-name: "@orbit/jsonapi"
    versions:
    - 0.17.0-beta.10
    - 0.17.0-beta.9
  - dependency-name: "@orbit/coordinator"
    versions:
    - 0.17.0-beta.9
  - dependency-name: "@sentry/integrations"
    versions:
    - 6.3.0
    - 6.3.2
  - dependency-name: eslint-plugin-ember
    versions:
    - 10.4.0
  - dependency-name: color-name-list
    versions:
    - 8.3.0
  - dependency-name: "@tailwindcss/forms"
    versions:
    - 0.3.1
  - dependency-name: ember-cli-babel
    versions:
    - 7.26.2
