name: swach
version: ${SNAP_VERSION}
summary: A robust color management tool for the modern age.
description: |
  Swach is a powerful color management tool designed for modern workflows. 
  Features include color palette management, contrast checking, and an eyedropper 
  tool for precise color picking from any part of your screen.

grade: stable
confinement: strict
base: core22
architectures:
  - build-on: amd64
  - build-on: arm64
title: Swach
contact: swach@shipshape.io
donation: https://buymeacoffee.com/shipshape
license: MIT
website: https://swach.io
issues: https://github.com/shipshapecode/swach/issues
source-code: https://github.com/shipshapecode/swach

plugs:
  shmem:
    interface: shared-memory
    private: true

apps:
  swach:
    command: bin/launcher
    desktop: usr/share/applications/swach.desktop
    extensions:
      - gnome
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
    plugs:
      - audio-record
      - audio-playback
      - screencast-legacy
      - desktop
      - desktop-legacy
      - home
      - network
      - x11
      - wayland
      - opengl
      - screen-inhibit-control
      - shmem

parts:
  launcher:
    plugin: dump
    source: snap/local
    source-type: local

  swach:
    plugin: dump
    source:
      - on amd64: out/make/deb/x64/swach_${SNAP_VERSION}_amd64.deb
      - on arm64: out/make/deb/arm64/swach_${SNAP_VERSION}_arm64.deb
    override-prime: |
      craftctl default
      # Fix desktop file to use launcher instead of direct path
      if [ -f usr/share/applications/swach.desktop ]; then
        sed -i 's|Exec=/usr/lib/swach/Swach.*|Exec=swach %U|g' usr/share/applications/swach.desktop
      fi
      # Fix chrome-sandbox permissions - remove setuid bit
      if [ -f usr/lib/swach/chrome-sandbox ]; then
        chmod 755 usr/lib/swach/chrome-sandbox
      fi
    stage-packages:
      - libasound2
      - libatk-bridge2.0-0
      - libdrm2
      - libgbm1
      - libgtk-3-0
      - libnss3
      - libxcomposite1
      - libxdamage1
      - libxfixes3
      - libxrandr2
      - libxss1
      - libxtst6

lint:
  ignore:
    - library:
        - usr/lib/*/libssl.so*
        - usr/lib/*/libcrypto.so*
    - classic
